import { toUTC } from "@/helper";

export function generateGPX(trackpoints, options = {}) {  
  const {
    name = "ReTrack Activity",
    desc = "Generated by ReTrack",
    type = "running",
    author = "Garmin Forerunner 55",
    time = trackpoints[0]?.time,
  } = options;

  const header = `<?xml version="1.0" encoding="UTF-8"?>
<gpx version="1.1" creator="${author}"
xmlns="http://www.topografix.com/GPX/1/1"
xmlns:gpxtpx="http://www.garmin.com/xmlschemas/TrackPointExtension/v1">

<metadata>
  <name>${name}</name>
  <desc>${desc}</desc>
  <time>${time}</time>
  <author>
    <name>ReTrack App</name>
    <link href="https://retrack.runminders.com"/>
  </author>
</metadata>

<trk>
  <name>${name}</name>
  <type>${type}</type>
  <trkseg>`;

  const footer = `
  </trkseg>
</trk>
</gpx>`;

  const points = trackpoints
    .map((p) => {
      const hrLine = p.hr != null ? `\n          <gpxtpx:hr>${p.hr}</gpxtpx:hr>` : '';
      const cadLine = p.cadence != null ? `\n          <gpxtpx:cad>${p.cadence}</gpxtpx:cad>` : '';
      const extensions = hrLine || cadLine
        ? `\n      <extensions>\n        <gpxtpx:TrackPointExtension>${hrLine}${cadLine}\n        </gpxtpx:TrackPointExtension>\n      </extensions>`
        : '';
      return `
    <trkpt lat="${p.lat}" lon="${p.lng}">
      <time>${p.time}</time>${extensions}
    </trkpt>`;
    })
    .join("");

  return header + points + footer;
}

export function downloadGPX(gpxString, filename = "activity.gpx") {
  const blob = new Blob([gpxString], { type: "application/gpx+xml" });
  const url = URL.createObjectURL(blob);

  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();

  URL.revokeObjectURL(url);
}